FROM golang:1.18 as builder

WORKDIR /app

COPY . .

RUN go mod init desafio/docker-golang

RUN apt-get update && apt-get install -f -y upx
RUN go build -a -gcflags=all="-l -B" -ldflags="-w -s" -o fullcycle
RUN upx fullcycle

FROM busybox:stable-musl

WORKDIR /app

COPY --from=builder /app/fullcycle .

#CMD ["tail","-f","/dev/null"]
ENTRYPOINT ["./fullcycle"] 